package user

// Code generated by gowrap. DO NOT EDIT.
// template:
// gowrap: http://github.com/fitan/gowrap

import (
	"context"
	"hello/pkg/ent"
	"hello/utils/log"

	"go.uber.org/zap"
)

// UserServiceWithLog implements UserService that is instrumented with logging
type UserServiceWithLog struct {
	_log  *zap.SugaredLogger
	_base UserService
}

// NewUserServiceWithLog instruments an implementation of the UserService with simple logging
func NewUserServiceWithLog(base UserService, log *zap.SugaredLogger) UserServiceWithLog {
	return UserServiceWithLog{
		_base: base,
		_log:  log,
	}
}

// DeleteById implements UserService
func (_d UserServiceWithLog) DeleteById(ctx context.Context, id int) (err error) {

	_log := _d._log.With(log.TraceId(ctx))

	defer func() {
		_log.Debugw("UserServiceWithLog calling DeleteById", "params", map[string]interface{}{
			"id": id}, "results", map[string]interface{}{
			"err": err})
		if err != nil {
			_log.Errorw("with_log", "params", map[string]interface{}{
				"id": id}, "results", map[string]interface{}{
				"err": err})
		}

	}()
	return _d._base.DeleteById(ctx, id)
}

// GetById implements UserService
func (_d UserServiceWithLog) GetById(ctx context.Context, id int) (up1 *ent.User, err error) {

	_log := _d._log.With(log.TraceId(ctx))

	defer func() {
		_log.Debugw("UserServiceWithLog calling GetById", "params", map[string]interface{}{
			"id": id}, "results", map[string]interface{}{
			"up1": up1,
			"err": err})
		if err != nil {
			_log.Errorw("with_log", "params", map[string]interface{}{
				"id": id}, "results", map[string]interface{}{
				"up1": up1,
				"err": err})
		}

	}()
	return _d._base.GetById(ctx, id)
}

// GetList implements UserService
func (_d UserServiceWithLog) GetList(ctx context.Context) (upa1 []*ent.User, err error) {

	_log := _d._log.With(log.TraceId(ctx))

	defer func() {
		_log.Debugw("UserServiceWithLog calling GetList", "params", map[string]interface{}{}, "results", map[string]interface{}{
			"upa1": upa1,
			"err":  err})
		if err != nil {
			_log.Errorw("with_log", "params", map[string]interface{}{}, "results", map[string]interface{}{
				"upa1": upa1,
				"err":  err})
		}

	}()
	return _d._base.GetList(ctx)
}

// Update implements UserService
func (_d UserServiceWithLog) Update(ctx context.Context, u *ent.User) (up1 *ent.User, err error) {

	_log := _d._log.With(log.TraceId(ctx))

	defer func() {
		_log.Debugw("UserServiceWithLog calling Update", "params", map[string]interface{}{
			"u": u}, "results", map[string]interface{}{
			"up1": up1,
			"err": err})
		if err != nil {
			_log.Errorw("with_log", "params", map[string]interface{}{
				"u": u}, "results", map[string]interface{}{
				"up1": up1,
				"err": err})
		}

	}()
	return _d._base.Update(ctx, u)
}
