package say

// Code generated by gowrap. DO NOT EDIT.
// template:
// gowrap: http://github.com/fitan/gowrap

import (
	"go.opentelemetry.io/otel/trace"
	"go.uber.org/zap"

	"context"

	"hello/pkg/ent"
)

// SayServiceWithLog implements SayService that is instrumented with logging
type SayServiceWithLog struct {
	_log  *zap.SugaredLogger
	_base SayService
}

// NewSayServiceWithLog instruments an implementation of the SayService with simple logging
func NewSayServiceWithLog(base SayService, log *zap.SugaredLogger) SayServiceWithLog {
	return SayServiceWithLog{
		_base: base,
		_log:  log,
	}
}

// SayPod implements SayService
func (_d SayServiceWithLog) SayPod(ctx context.Context, req SayPodReq) (pp1 *ent.Pod, err error) {

	_log := _d._log.With(zap.String("traceId", trace.SpanFromContext(ctx).SpanContext().TraceID().String()))

	defer func() {
		_log.Debugw("SayServiceWithLog calling SayPod", "params", map[string]interface{}{
			"req": req}, "results", map[string]interface{}{
			"pp1": pp1,
			"err": err})
		if err != nil {
			_log.Errorw("with_log", "params", map[string]interface{}{
				"req": req}, "results", map[string]interface{}{
				"pp1": pp1,
				"err": err})
		}

	}()
	return _d._base.SayPod(ctx, req)
}
