version: '3'
tasks:
  default:
    cmds:
      - task --list-all
  ent:
    dir: "./pkg/ent"
    cmds:
      - go generate
  build:
    cmds:
      - go build -ldflags "-X main.GitCommitId=`git rev-parse HEAD` -X 'main.goVersion=$(go version)' -X 'main.gitHash=$(git show -s --format=%H)' -X 'main.buildTime=$(git show -s --format=%cd)'"  -mod vendor -o output/main ./cmd/main.go
  wire:
    dir: ./cmd/app/
    cmds:
      - wire
  run:
    cmds:
      - go run cmd/main.go {{.CLI_ARGS}}
  conf:
    cmds:
      - vim conf/dev.conf.yaml
    interactive: true
  init:s:
    dir: "./pkg/services"
    cmds:
      - gowrap gen -init kit -n {{.CLI_ARGS}}
  init:a:
    dir: "./pkg/repository/api"
    cmds:
      - gowrap gen -init service -n {{.CLI_ARGS}}
  init:d:
    dir: "./pkg/repository/dao"
    cmds:
      - gowrap gen -init service -n {{.CLI_ARGS}}
  swag:
    cmds:
      - swag init -g cmd/main.go  -d ./