version: '3'
tasks:
  run:
    cmds:
      - go run cmd/main.go
  conf:
    cmds:
      - vim conf/dev.conf.yaml
    interactive: true
  gens:
    dir: "./pkg/services"
    cmds:
      - gowrap gen -init {{.CLI_ARGS}}