package baidu

// Code generated by gowrap. DO NOT EDIT.
// template: ../../../gowrap/templates/log.tmpl
// gowrap: http://github.com/fitan/gowrap

import (
	"context"
	"hello/utils/log"

	"github.com/go-resty/resty/v2"
	"go.uber.org/zap"
)

// BaiduApiWithLog implements BaiduApi that is instrumented with logging
type BaiduApiWithLog struct {
	_log  *zap.SugaredLogger
	_base BaiduApi
}

// NewBaiduApiWithLog instruments an implementation of the BaiduApi with simple logging
func NewBaiduApiWithLog(base BaiduApi, log *zap.SugaredLogger) BaiduApiWithLog {
	return BaiduApiWithLog{
		_base: base,
		_log:  log,
	}
}

// GetRoot implements BaiduApi
func (_d BaiduApiWithLog) GetRoot(ctx context.Context) (rp1 *resty.Response, err error) {

	_log := _d._log.With(log.TraceId(ctx))

	defer func() {
		_log.Debugw("BaiduApiWithLog calling GetRoot", "params", map[string]interface{}{}, "results", map[string]interface{}{
			"rp1": rp1,
			"err": err})
		if err != nil {
			_log.Errorw("with_log", "params", map[string]interface{}{}, "results", map[string]interface{}{
				"rp1": rp1,
				"err": err})
		}

	}()
	return _d._base.GetRoot(ctx)
}

// GetRoot1 implements BaiduApi
func (_d BaiduApiWithLog) GetRoot1(ctx context.Context) (rp1 *resty.Response, err error) {

	_log := _d._log.With(log.TraceId(ctx))

	defer func() {
		_log.Debugw("BaiduApiWithLog calling GetRoot1", "params", map[string]interface{}{}, "results", map[string]interface{}{
			"rp1": rp1,
			"err": err})
		if err != nil {
			_log.Errorw("with_log", "params", map[string]interface{}{}, "results", map[string]interface{}{
				"rp1": rp1,
				"err": err})
		}

	}()
	return _d._base.GetRoot1(ctx)
}
