package pod

// Code generated by gowrap. DO NOT EDIT.
// template:
// gowrap: http://github.com/fitan/gowrap

import (
	"time"

	"context"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"

	"hello/pkg/ent"
)

// PodServiceWithPrometheus implements PodService interface with all methods wrapped
// with Prometheus metrics
type PodServiceWithPrometheus struct {
	base         PodService
	instanceName string
}

var podserviceDurationSummaryVec = promauto.NewSummaryVec(
	prometheus.SummaryOpts{
		Name:       "dao_pod_duration_seconds",
		Help:       "podservice runtime duration and result",
		MaxAge:     time.Minute,
		Objectives: map[float64]float64{0.5: 0.05, 0.9: 0.01, 0.99: 0.001},
	},
	[]string{"instance_name", "method", "result"})

// NewPodServiceWithPrometheus returns an instance of the PodService decorated with prometheus summary metric
func NewPodServiceWithPrometheus(base PodService) PodServiceWithPrometheus {
	return PodServiceWithPrometheus{
		base:         base,
		instanceName: "podservice",
	}
}

// ByQueries implements PodService
func (_d PodServiceWithPrometheus) ByQueries(ctx context.Context, i interface{}) (res ent.Pods, count int, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		podserviceDurationSummaryVec.WithLabelValues(_d.instanceName, "ByQueries", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.ByQueries(ctx, i)
}

// Create implements PodService
func (_d PodServiceWithPrometheus) Create(ctx context.Context, v *ent.Pod) (res *ent.Pod, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		podserviceDurationSummaryVec.WithLabelValues(_d.instanceName, "Create", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.Create(ctx, v)
}

// CreateMany implements PodService
func (_d PodServiceWithPrometheus) CreateMany(ctx context.Context, vs ent.Pods) (p1 ent.Pods, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		podserviceDurationSummaryVec.WithLabelValues(_d.instanceName, "CreateMany", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.CreateMany(ctx, vs)
}

// CreateServicetreeByPodId implements PodService
func (_d PodServiceWithPrometheus) CreateServicetreeByPodId(ctx context.Context, id int64, v *ent.SpiderDevTblServicetree) (res *ent.Pod, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		podserviceDurationSummaryVec.WithLabelValues(_d.instanceName, "CreateServicetreeByPodId", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.CreateServicetreeByPodId(ctx, id, v)
}

// DeleteById implements PodService
func (_d PodServiceWithPrometheus) DeleteById(ctx context.Context, id int64) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		podserviceDurationSummaryVec.WithLabelValues(_d.instanceName, "DeleteById", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.DeleteById(ctx, id)
}

// DeleteMany implements PodService
func (_d PodServiceWithPrometheus) DeleteMany(ctx context.Context, ids []int64) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		podserviceDurationSummaryVec.WithLabelValues(_d.instanceName, "DeleteMany", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.DeleteMany(ctx, ids)
}

// GetById implements PodService
func (_d PodServiceWithPrometheus) GetById(ctx context.Context, id int64) (res *ent.Pod, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		podserviceDurationSummaryVec.WithLabelValues(_d.instanceName, "GetById", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetById(ctx, id)
}

// GetServicetreeByPodId implements PodService
func (_d PodServiceWithPrometheus) GetServicetreeByPodId(ctx context.Context, id int64) (res *ent.SpiderDevTblServicetree, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		podserviceDurationSummaryVec.WithLabelValues(_d.instanceName, "GetServicetreeByPodId", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.GetServicetreeByPodId(ctx, id)
}

// UpdateById implements PodService
func (_d PodServiceWithPrometheus) UpdateById(ctx context.Context, id int64, v *ent.Pod) (pp1 *ent.Pod, err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		podserviceDurationSummaryVec.WithLabelValues(_d.instanceName, "UpdateById", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.UpdateById(ctx, id, v)
}

// UpdateMany implements PodService
func (_d PodServiceWithPrometheus) UpdateMany(ctx context.Context, vs ent.Pods) (err error) {
	_since := time.Now()
	defer func() {
		result := "ok"
		if err != nil {
			result = "error"
		}

		podserviceDurationSummaryVec.WithLabelValues(_d.instanceName, "UpdateMany", result).Observe(time.Since(_since).Seconds())
	}()
	return _d.base.UpdateMany(ctx, vs)
}
