package pod

// Code generated by gowrap. DO NOT EDIT.
// template:
// gowrap: http://github.com/fitan/gowrap

import (
	"context"

	"go.opentelemetry.io/otel/trace"
	"go.uber.org/zap"

	"hello/pkg/ent"
)

// PodServiceWithLog implements PodService that is instrumented with logging
type PodServiceWithLog struct {
	_log  *zap.SugaredLogger
	_base PodService
}

// NewPodServiceWithLog instruments an implementation of the PodService with simple logging
func NewPodServiceWithLog(base PodService, log *zap.SugaredLogger) PodServiceWithLog {
	return PodServiceWithLog{
		_base: base,
		_log:  log,
	}
}

// ByQueries implements PodService
func (_d PodServiceWithLog) ByQueries(ctx context.Context, i interface{}) (res ent.Pods, count int, err error) {

	_log := _d._log.With(zap.String("traceId", trace.SpanFromContext(ctx).SpanContext().TraceID().String()))

	defer func() {
		_log.Debugw("PodServiceWithLog calling ByQueries", "params", map[string]interface{}{
			"i": i}, "results", map[string]interface{}{
			"res":   res,
			"count": count,
			"err":   err})
		if err != nil {
			_log.Errorw("with_log", "params", map[string]interface{}{
				"i": i}, "results", map[string]interface{}{
				"res":   res,
				"count": count,
				"err":   err})
		}

	}()
	return _d._base.ByQueries(ctx, i)
}

// Create implements PodService
func (_d PodServiceWithLog) Create(ctx context.Context, v ent.Pod) (res *ent.Pod, err error) {

	_log := _d._log.With(zap.String("traceId", trace.SpanFromContext(ctx).SpanContext().TraceID().String()))

	defer func() {
		_log.Debugw("PodServiceWithLog calling Create", "params", map[string]interface{}{
			"v": v}, "results", map[string]interface{}{
			"res": res,
			"err": err})
		if err != nil {
			_log.Errorw("with_log", "params", map[string]interface{}{
				"v": v}, "results", map[string]interface{}{
				"res": res,
				"err": err})
		}

	}()
	return _d._base.Create(ctx, v)
}

// CreateMany implements PodService
func (_d PodServiceWithLog) CreateMany(ctx context.Context, vs ent.Pods) (p1 ent.Pods, err error) {

	_log := _d._log.With(zap.String("traceId", trace.SpanFromContext(ctx).SpanContext().TraceID().String()))

	defer func() {
		_log.Debugw("PodServiceWithLog calling CreateMany", "params", map[string]interface{}{
			"vs": vs}, "results", map[string]interface{}{
			"p1":  p1,
			"err": err})
		if err != nil {
			_log.Errorw("with_log", "params", map[string]interface{}{
				"vs": vs}, "results", map[string]interface{}{
				"p1":  p1,
				"err": err})
		}

	}()
	return _d._base.CreateMany(ctx, vs)
}

// CreateServicetreeByPodId implements PodService
func (_d PodServiceWithLog) CreateServicetreeByPodId(ctx context.Context, id int64, v *ent.SpiderDevTblServicetree) (res *ent.Pod, err error) {

	_log := _d._log.With(zap.String("traceId", trace.SpanFromContext(ctx).SpanContext().TraceID().String()))

	defer func() {
		_log.Debugw("PodServiceWithLog calling CreateServicetreeByPodId", "params", map[string]interface{}{
			"id": id,
			"v":  v}, "results", map[string]interface{}{
			"res": res,
			"err": err})
		if err != nil {
			_log.Errorw("with_log", "params", map[string]interface{}{
				"id": id,
				"v":  v}, "results", map[string]interface{}{
				"res": res,
				"err": err})
		}

	}()
	return _d._base.CreateServicetreeByPodId(ctx, id, v)
}

// DeleteById implements PodService
func (_d PodServiceWithLog) DeleteById(ctx context.Context, id int64) (err error) {

	_log := _d._log.With(zap.String("traceId", trace.SpanFromContext(ctx).SpanContext().TraceID().String()))

	defer func() {
		_log.Debugw("PodServiceWithLog calling DeleteById", "params", map[string]interface{}{
			"id": id}, "results", map[string]interface{}{
			"err": err})
		if err != nil {
			_log.Errorw("with_log", "params", map[string]interface{}{
				"id": id}, "results", map[string]interface{}{
				"err": err})
		}

	}()
	return _d._base.DeleteById(ctx, id)
}

// DeleteMany implements PodService
func (_d PodServiceWithLog) DeleteMany(ctx context.Context, ids []int64) (err error) {

	_log := _d._log.With(zap.String("traceId", trace.SpanFromContext(ctx).SpanContext().TraceID().String()))

	defer func() {
		_log.Debugw("PodServiceWithLog calling UserRestDeleteMany", "params", map[string]interface{}{
			"ids": ids}, "results", map[string]interface{}{
			"err": err})
		if err != nil {
			_log.Errorw("with_log", "params", map[string]interface{}{
				"ids": ids}, "results", map[string]interface{}{
				"err": err})
		}

	}()
	return _d._base.DeleteMany(ctx, ids)
}

// GetById implements PodService
func (_d PodServiceWithLog) GetById(ctx context.Context, id int64) (res *ent.Pod, err error) {

	_log := _d._log.With(zap.String("traceId", trace.SpanFromContext(ctx).SpanContext().TraceID().String()))

	defer func() {
		_log.Debugw("PodServiceWithLog calling GetById", "params", map[string]interface{}{
			"id": id}, "results", map[string]interface{}{
			"res": res,
			"err": err})
		if err != nil {
			_log.Errorw("with_log", "params", map[string]interface{}{
				"id": id}, "results", map[string]interface{}{
				"res": res,
				"err": err})
		}

	}()
	return _d._base.GetById(ctx, id)
}

// GetServicetreeByPodId implements PodService
func (_d PodServiceWithLog) GetServicetreeByPodId(ctx context.Context, id int64) (res *ent.SpiderDevTblServicetree, err error) {

	_log := _d._log.With(zap.String("traceId", trace.SpanFromContext(ctx).SpanContext().TraceID().String()))

	defer func() {
		_log.Debugw("PodServiceWithLog calling GetServicetreeByPodId", "params", map[string]interface{}{
			"id": id}, "results", map[string]interface{}{
			"res": res,
			"err": err})
		if err != nil {
			_log.Errorw("with_log", "params", map[string]interface{}{
				"id": id}, "results", map[string]interface{}{
				"res": res,
				"err": err})
		}

	}()
	return _d._base.GetServicetreeByPodId(ctx, id)
}

// UpdateById implements PodService
func (_d PodServiceWithLog) UpdateById(ctx context.Context, id int64, v *ent.Pod) (pp1 *ent.Pod, err error) {

	_log := _d._log.With(zap.String("traceId", trace.SpanFromContext(ctx).SpanContext().TraceID().String()))

	defer func() {
		_log.Debugw("PodServiceWithLog calling UpdateById", "params", map[string]interface{}{
			"id": id,
			"v":  v}, "results", map[string]interface{}{
			"pp1": pp1,
			"err": err})
		if err != nil {
			_log.Errorw("with_log", "params", map[string]interface{}{
				"id": id,
				"v":  v}, "results", map[string]interface{}{
				"pp1": pp1,
				"err": err})
		}

	}()
	return _d._base.UpdateById(ctx, id, v)
}

// UpdateMany implements PodService
func (_d PodServiceWithLog) UpdateMany(ctx context.Context, vs ent.Pods) (err error) {

	_log := _d._log.With(zap.String("traceId", trace.SpanFromContext(ctx).SpanContext().TraceID().String()))

	defer func() {
		_log.Debugw("PodServiceWithLog calling UpdateMany", "params", map[string]interface{}{
			"vs": vs}, "results", map[string]interface{}{
			"err": err})
		if err != nil {
			_log.Errorw("with_log", "params", map[string]interface{}{
				"vs": vs}, "results", map[string]interface{}{
				"err": err})
		}

	}()
	return _d._base.UpdateMany(ctx, vs)
}
