package service

// Code generated by gowrap. DO NOT EDIT.
// template:
// gowrap: http://github.com/fitan/gowrap

import (
	"encoding/json"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/codes"
	semconv "go.opentelemetry.io/otel/semconv/v1.7.0"
	"go.opentelemetry.io/otel/trace"

	"context"

	"hello/pkg/ent"
)

// ServiceServiceWithTracing implements ServiceService interface instrumented with opentracing spans
type ServiceServiceWithTracing struct {
	ServiceService
}

// NewServiceServiceWithTracing returns ServiceServiceWithTracing
func NewServiceServiceWithTracing(base ServiceService) ServiceService {
	d := ServiceServiceWithTracing{
		ServiceService: base,
	}

	return d
}

// ByQueriesAll implements ServiceService
func (_d ServiceServiceWithTracing) ByQueriesAll(ctx context.Context, i interface{}) (res []ent.ServiceBaseGetRes, count int, err error) {

	var name = "ServiceService.ByQueriesAll"
	_, span := otel.Tracer(name).Start(ctx, name)
	defer func() {
		if err != nil {
			l := map[string]interface{}{
				"params": map[string]interface{}{
					"i": i},
				"result": map[string]interface{}{
					"res":   res,
					"count": count,
					"err":   err},
			}
			s, _ := json.Marshal(l)
			span.AddEvent(semconv.ExceptionEventName, trace.WithAttributes(semconv.ExceptionTypeKey.String("context"), semconv.ExceptionMessageKey.String(string(s))))
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()

	return _d.ServiceService.ByQueriesAll(ctx, i)
}

// ByQueriesOne implements ServiceService
func (_d ServiceServiceWithTracing) ByQueriesOne(ctx context.Context, i interface{}) (res ent.ServiceBaseGetRes, err error) {

	var name = "ServiceService.ByQueriesOne"
	_, span := otel.Tracer(name).Start(ctx, name)
	defer func() {
		if err != nil {
			l := map[string]interface{}{
				"params": map[string]interface{}{
					"i": i},
				"result": map[string]interface{}{
					"res": res,
					"err": err},
			}
			s, _ := json.Marshal(l)
			span.AddEvent(semconv.ExceptionEventName, trace.WithAttributes(semconv.ExceptionTypeKey.String("context"), semconv.ExceptionMessageKey.String(string(s))))
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()

	return _d.ServiceService.ByQueriesOne(ctx, i)
}

// Create implements ServiceService
func (_d ServiceServiceWithTracing) Create(ctx context.Context, v ent.ServiceBaseCreateReq) (res *ent.Service, err error) {

	var name = "ServiceService.Create"
	_, span := otel.Tracer(name).Start(ctx, name)
	defer func() {
		if err != nil {
			l := map[string]interface{}{
				"params": map[string]interface{}{
					"v": v},
				"result": map[string]interface{}{
					"res": res,
					"err": err},
			}
			s, _ := json.Marshal(l)
			span.AddEvent(semconv.ExceptionEventName, trace.WithAttributes(semconv.ExceptionTypeKey.String("context"), semconv.ExceptionMessageKey.String(string(s))))
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()

	return _d.ServiceService.Create(ctx, v)
}

// CreateMany implements ServiceService
func (_d ServiceServiceWithTracing) CreateMany(ctx context.Context, vs []ent.ServiceBaseCreateReq) (s1 ent.Services, err error) {

	var name = "ServiceService.CreateMany"
	_, span := otel.Tracer(name).Start(ctx, name)
	defer func() {
		if err != nil {
			l := map[string]interface{}{
				"params": map[string]interface{}{
					"vs": vs},
				"result": map[string]interface{}{
					"s1":  s1,
					"err": err},
			}
			s, _ := json.Marshal(l)
			span.AddEvent(semconv.ExceptionEventName, trace.WithAttributes(semconv.ExceptionTypeKey.String("context"), semconv.ExceptionMessageKey.String(string(s))))
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()

	return _d.ServiceService.CreateMany(ctx, vs)
}

// CreateProjectByServiceId implements ServiceService
func (_d ServiceServiceWithTracing) CreateProjectByServiceId(ctx context.Context, id int, v ent.ProjectBaseCreateReq) (res *ent.Service, err error) {

	var name = "ServiceService.CreateProjectByServiceId"
	_, span := otel.Tracer(name).Start(ctx, name)
	defer func() {
		if err != nil {
			l := map[string]interface{}{
				"params": map[string]interface{}{
					"id": id,
					"v":  v},
				"result": map[string]interface{}{
					"res": res,
					"err": err},
			}
			s, _ := json.Marshal(l)
			span.AddEvent(semconv.ExceptionEventName, trace.WithAttributes(semconv.ExceptionTypeKey.String("context"), semconv.ExceptionMessageKey.String(string(s))))
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()

	return _d.ServiceService.CreateProjectByServiceId(ctx, id, v)
}

// DeleteById implements ServiceService
func (_d ServiceServiceWithTracing) DeleteById(ctx context.Context, id int) (err error) {

	var name = "ServiceService.DeleteById"
	_, span := otel.Tracer(name).Start(ctx, name)
	defer func() {
		if err != nil {
			l := map[string]interface{}{
				"params": map[string]interface{}{
					"id": id},
				"result": map[string]interface{}{
					"err": err},
			}
			s, _ := json.Marshal(l)
			span.AddEvent(semconv.ExceptionEventName, trace.WithAttributes(semconv.ExceptionTypeKey.String("context"), semconv.ExceptionMessageKey.String(string(s))))
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()

	return _d.ServiceService.DeleteById(ctx, id)
}

// DeleteMany implements ServiceService
func (_d ServiceServiceWithTracing) DeleteMany(ctx context.Context, ids []int) (err error) {

	var name = "ServiceService.DeleteMany"
	_, span := otel.Tracer(name).Start(ctx, name)
	defer func() {
		if err != nil {
			l := map[string]interface{}{
				"params": map[string]interface{}{
					"ids": ids},
				"result": map[string]interface{}{
					"err": err},
			}
			s, _ := json.Marshal(l)
			span.AddEvent(semconv.ExceptionEventName, trace.WithAttributes(semconv.ExceptionTypeKey.String("context"), semconv.ExceptionMessageKey.String(string(s))))
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()

	return _d.ServiceService.DeleteMany(ctx, ids)
}

// GetById implements ServiceService
func (_d ServiceServiceWithTracing) GetById(ctx context.Context, id int) (res ent.ServiceBaseGetRes, err error) {

	var name = "ServiceService.GetById"
	_, span := otel.Tracer(name).Start(ctx, name)
	defer func() {
		if err != nil {
			l := map[string]interface{}{
				"params": map[string]interface{}{
					"id": id},
				"result": map[string]interface{}{
					"res": res,
					"err": err},
			}
			s, _ := json.Marshal(l)
			span.AddEvent(semconv.ExceptionEventName, trace.WithAttributes(semconv.ExceptionTypeKey.String("context"), semconv.ExceptionMessageKey.String(string(s))))
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()

	return _d.ServiceService.GetById(ctx, id)
}

// GetProjectByServiceId implements ServiceService
func (_d ServiceServiceWithTracing) GetProjectByServiceId(ctx context.Context, id int) (res ent.ProjectBaseGetRes, err error) {

	var name = "ServiceService.GetProjectByServiceId"
	_, span := otel.Tracer(name).Start(ctx, name)
	defer func() {
		if err != nil {
			l := map[string]interface{}{
				"params": map[string]interface{}{
					"id": id},
				"result": map[string]interface{}{
					"res": res,
					"err": err},
			}
			s, _ := json.Marshal(l)
			span.AddEvent(semconv.ExceptionEventName, trace.WithAttributes(semconv.ExceptionTypeKey.String("context"), semconv.ExceptionMessageKey.String(string(s))))
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()

	return _d.ServiceService.GetProjectByServiceId(ctx, id)
}

// RawAddBindProjectByServiceId implements ServiceService
func (_d ServiceServiceWithTracing) RawAddBindProjectByServiceId(ctx context.Context, id int, addId int) (err error) {

	var name = "ServiceService.RawAddBindProjectByServiceId"
	_, span := otel.Tracer(name).Start(ctx, name)
	defer func() {
		if err != nil {
			l := map[string]interface{}{
				"params": map[string]interface{}{
					"id":    id,
					"addId": addId},
				"result": map[string]interface{}{
					"err": err},
			}
			s, _ := json.Marshal(l)
			span.AddEvent(semconv.ExceptionEventName, trace.WithAttributes(semconv.ExceptionTypeKey.String("context"), semconv.ExceptionMessageKey.String(string(s))))
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()

	return _d.ServiceService.RawAddBindProjectByServiceId(ctx, id, addId)
}

// RawByQueriesAll implements ServiceService
func (_d ServiceServiceWithTracing) RawByQueriesAll(ctx context.Context, i interface{}) (res ent.Services, count int, err error) {

	var name = "ServiceService.RawByQueriesAll"
	_, span := otel.Tracer(name).Start(ctx, name)
	defer func() {
		if err != nil {
			l := map[string]interface{}{
				"params": map[string]interface{}{
					"i": i},
				"result": map[string]interface{}{
					"res":   res,
					"count": count,
					"err":   err},
			}
			s, _ := json.Marshal(l)
			span.AddEvent(semconv.ExceptionEventName, trace.WithAttributes(semconv.ExceptionTypeKey.String("context"), semconv.ExceptionMessageKey.String(string(s))))
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()

	return _d.ServiceService.RawByQueriesAll(ctx, i)
}

// RawByQueriesOne implements ServiceService
func (_d ServiceServiceWithTracing) RawByQueriesOne(ctx context.Context, i interface{}) (res *ent.Service, err error) {

	var name = "ServiceService.RawByQueriesOne"
	_, span := otel.Tracer(name).Start(ctx, name)
	defer func() {
		if err != nil {
			l := map[string]interface{}{
				"params": map[string]interface{}{
					"i": i},
				"result": map[string]interface{}{
					"res": res,
					"err": err},
			}
			s, _ := json.Marshal(l)
			span.AddEvent(semconv.ExceptionEventName, trace.WithAttributes(semconv.ExceptionTypeKey.String("context"), semconv.ExceptionMessageKey.String(string(s))))
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()

	return _d.ServiceService.RawByQueriesOne(ctx, i)
}

// RawCreate implements ServiceService
func (_d ServiceServiceWithTracing) RawCreate(ctx context.Context, v *ent.Service) (res *ent.Service, err error) {

	var name = "ServiceService.RawCreate"
	_, span := otel.Tracer(name).Start(ctx, name)
	defer func() {
		if err != nil {
			l := map[string]interface{}{
				"params": map[string]interface{}{
					"v": v},
				"result": map[string]interface{}{
					"res": res,
					"err": err},
			}
			s, _ := json.Marshal(l)
			span.AddEvent(semconv.ExceptionEventName, trace.WithAttributes(semconv.ExceptionTypeKey.String("context"), semconv.ExceptionMessageKey.String(string(s))))
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()

	return _d.ServiceService.RawCreate(ctx, v)
}

// RawCreateMany implements ServiceService
func (_d ServiceServiceWithTracing) RawCreateMany(ctx context.Context, vs ent.Services) (s1 ent.Services, err error) {

	var name = "ServiceService.RawCreateMany"
	_, span := otel.Tracer(name).Start(ctx, name)
	defer func() {
		if err != nil {
			l := map[string]interface{}{
				"params": map[string]interface{}{
					"vs": vs},
				"result": map[string]interface{}{
					"s1":  s1,
					"err": err},
			}
			s, _ := json.Marshal(l)
			span.AddEvent(semconv.ExceptionEventName, trace.WithAttributes(semconv.ExceptionTypeKey.String("context"), semconv.ExceptionMessageKey.String(string(s))))
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()

	return _d.ServiceService.RawCreateMany(ctx, vs)
}

// RawCreateProjectByServiceId implements ServiceService
func (_d ServiceServiceWithTracing) RawCreateProjectByServiceId(ctx context.Context, id int, v *ent.Project) (res *ent.Service, err error) {

	var name = "ServiceService.RawCreateProjectByServiceId"
	_, span := otel.Tracer(name).Start(ctx, name)
	defer func() {
		if err != nil {
			l := map[string]interface{}{
				"params": map[string]interface{}{
					"id": id,
					"v":  v},
				"result": map[string]interface{}{
					"res": res,
					"err": err},
			}
			s, _ := json.Marshal(l)
			span.AddEvent(semconv.ExceptionEventName, trace.WithAttributes(semconv.ExceptionTypeKey.String("context"), semconv.ExceptionMessageKey.String(string(s))))
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()

	return _d.ServiceService.RawCreateProjectByServiceId(ctx, id, v)
}

// RawDeleteProjectByServiceId implements ServiceService
func (_d ServiceServiceWithTracing) RawDeleteProjectByServiceId(ctx context.Context, id int, deleteId int) (err error) {

	var name = "ServiceService.RawDeleteProjectByServiceId"
	_, span := otel.Tracer(name).Start(ctx, name)
	defer func() {
		if err != nil {
			l := map[string]interface{}{
				"params": map[string]interface{}{
					"id":       id,
					"deleteId": deleteId},
				"result": map[string]interface{}{
					"err": err},
			}
			s, _ := json.Marshal(l)
			span.AddEvent(semconv.ExceptionEventName, trace.WithAttributes(semconv.ExceptionTypeKey.String("context"), semconv.ExceptionMessageKey.String(string(s))))
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()

	return _d.ServiceService.RawDeleteProjectByServiceId(ctx, id, deleteId)
}

// RawGetById implements ServiceService
func (_d ServiceServiceWithTracing) RawGetById(ctx context.Context, id int) (res *ent.Service, err error) {

	var name = "ServiceService.RawGetById"
	_, span := otel.Tracer(name).Start(ctx, name)
	defer func() {
		if err != nil {
			l := map[string]interface{}{
				"params": map[string]interface{}{
					"id": id},
				"result": map[string]interface{}{
					"res": res,
					"err": err},
			}
			s, _ := json.Marshal(l)
			span.AddEvent(semconv.ExceptionEventName, trace.WithAttributes(semconv.ExceptionTypeKey.String("context"), semconv.ExceptionMessageKey.String(string(s))))
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()

	return _d.ServiceService.RawGetById(ctx, id)
}

// RawGetProjectByServiceId implements ServiceService
func (_d ServiceServiceWithTracing) RawGetProjectByServiceId(ctx context.Context, id int) (res *ent.Project, err error) {

	var name = "ServiceService.RawGetProjectByServiceId"
	_, span := otel.Tracer(name).Start(ctx, name)
	defer func() {
		if err != nil {
			l := map[string]interface{}{
				"params": map[string]interface{}{
					"id": id},
				"result": map[string]interface{}{
					"res": res,
					"err": err},
			}
			s, _ := json.Marshal(l)
			span.AddEvent(semconv.ExceptionEventName, trace.WithAttributes(semconv.ExceptionTypeKey.String("context"), semconv.ExceptionMessageKey.String(string(s))))
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()

	return _d.ServiceService.RawGetProjectByServiceId(ctx, id)
}

// RawRemoveBindProjectByServiceId implements ServiceService
func (_d ServiceServiceWithTracing) RawRemoveBindProjectByServiceId(ctx context.Context, id int) (err error) {

	var name = "ServiceService.RawRemoveBindProjectByServiceId"
	_, span := otel.Tracer(name).Start(ctx, name)
	defer func() {
		if err != nil {
			l := map[string]interface{}{
				"params": map[string]interface{}{
					"id": id},
				"result": map[string]interface{}{
					"err": err},
			}
			s, _ := json.Marshal(l)
			span.AddEvent(semconv.ExceptionEventName, trace.WithAttributes(semconv.ExceptionTypeKey.String("context"), semconv.ExceptionMessageKey.String(string(s))))
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()

	return _d.ServiceService.RawRemoveBindProjectByServiceId(ctx, id)
}

// RawUpdateBindProjectByServiceId implements ServiceService
func (_d ServiceServiceWithTracing) RawUpdateBindProjectByServiceId(ctx context.Context, id int, updateId int) (err error) {

	var name = "ServiceService.RawUpdateBindProjectByServiceId"
	_, span := otel.Tracer(name).Start(ctx, name)
	defer func() {
		if err != nil {
			l := map[string]interface{}{
				"params": map[string]interface{}{
					"id":       id,
					"updateId": updateId},
				"result": map[string]interface{}{
					"err": err},
			}
			s, _ := json.Marshal(l)
			span.AddEvent(semconv.ExceptionEventName, trace.WithAttributes(semconv.ExceptionTypeKey.String("context"), semconv.ExceptionMessageKey.String(string(s))))
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()

	return _d.ServiceService.RawUpdateBindProjectByServiceId(ctx, id, updateId)
}

// RawUpdateById implements ServiceService
func (_d ServiceServiceWithTracing) RawUpdateById(ctx context.Context, id int, v *ent.Service) (sp1 *ent.Service, err error) {

	var name = "ServiceService.RawUpdateById"
	_, span := otel.Tracer(name).Start(ctx, name)
	defer func() {
		if err != nil {
			l := map[string]interface{}{
				"params": map[string]interface{}{
					"id": id,
					"v":  v},
				"result": map[string]interface{}{
					"sp1": sp1,
					"err": err},
			}
			s, _ := json.Marshal(l)
			span.AddEvent(semconv.ExceptionEventName, trace.WithAttributes(semconv.ExceptionTypeKey.String("context"), semconv.ExceptionMessageKey.String(string(s))))
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()

	return _d.ServiceService.RawUpdateById(ctx, id, v)
}

// RawUpdateMany implements ServiceService
func (_d ServiceServiceWithTracing) RawUpdateMany(ctx context.Context, vs ent.Services) (err error) {

	var name = "ServiceService.RawUpdateMany"
	_, span := otel.Tracer(name).Start(ctx, name)
	defer func() {
		if err != nil {
			l := map[string]interface{}{
				"params": map[string]interface{}{
					"vs": vs},
				"result": map[string]interface{}{
					"err": err},
			}
			s, _ := json.Marshal(l)
			span.AddEvent(semconv.ExceptionEventName, trace.WithAttributes(semconv.ExceptionTypeKey.String("context"), semconv.ExceptionMessageKey.String(string(s))))
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()

	return _d.ServiceService.RawUpdateMany(ctx, vs)
}

// UpdateById implements ServiceService
func (_d ServiceServiceWithTracing) UpdateById(ctx context.Context, id int, v ent.ServiceBaseUpdateReq) (sp1 *ent.Service, err error) {

	var name = "ServiceService.UpdateById"
	_, span := otel.Tracer(name).Start(ctx, name)
	defer func() {
		if err != nil {
			l := map[string]interface{}{
				"params": map[string]interface{}{
					"id": id,
					"v":  v},
				"result": map[string]interface{}{
					"sp1": sp1,
					"err": err},
			}
			s, _ := json.Marshal(l)
			span.AddEvent(semconv.ExceptionEventName, trace.WithAttributes(semconv.ExceptionTypeKey.String("context"), semconv.ExceptionMessageKey.String(string(s))))
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()

	return _d.ServiceService.UpdateById(ctx, id, v)
}

// UpdateMany implements ServiceService
func (_d ServiceServiceWithTracing) UpdateMany(ctx context.Context, vs []ent.ServiceBaseUpdateReq) (err error) {

	var name = "ServiceService.UpdateMany"
	_, span := otel.Tracer(name).Start(ctx, name)
	defer func() {
		if err != nil {
			l := map[string]interface{}{
				"params": map[string]interface{}{
					"vs": vs},
				"result": map[string]interface{}{
					"err": err},
			}
			s, _ := json.Marshal(l)
			span.AddEvent(semconv.ExceptionEventName, trace.WithAttributes(semconv.ExceptionTypeKey.String("context"), semconv.ExceptionMessageKey.String(string(s))))
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()

	return _d.ServiceService.UpdateMany(ctx, vs)
}
